# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kyle Young
tagline:          'Personal Website'
description:      'Hi!  Welcome to my personal website.'
url:              http://kyle-young.github.io
baseurl:          /

author:
  name:           'Kyle Young'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
